### PR TITLE
inflection tables and improvements

### PR DESCRIPTION
**Pull request by garfieldnate**
* Support retrieving and printing German inflection tables for nouns, verbs and adjectives.
* Use ArgParse to parse args and generate documentation.
* Wait 1 second between calls to the Leo website to avoid spamming them.
* Don't barf errors when the user presses CTRL-C (especially important when piping to less).
* Add a `requirements.txt` file so users can install all dependencies with one command.

### CODE REVIEW

**Comment by garfieldnate** [comment]
I understand that this is a big PR and it is not perfect. This is the version that I am using now and I wanted to share it with you and other users. If you have questions or comments I can edit it more. If you don't want to merge it, I will understand that, as well. I ended up changing it pretty heavily!

The error catching was weird enough for me that I feel it needs an explanation:

I use leo-cli through a bash function that looks like this:

    function de() {
        leo $@ | less
    }

This is especially useful when looking up inflection tables, since the tool may return many tables and each one is quite long. However, if you look at just the first table and then quit `less` because you've seen enough, then Python ends up throwing weird errors (`KeyboardInterrupt`, `BrokenPipeError` and `IOError`, depending on Python version and the timing). These look really nasty to the user because they are printed as a big stack trace. They can also be thrown if the user quits while the `requests` library is being loaded. Different kinds of errors are raised depending on if you are quitting `less` or just typing CTRL-C, and the code I added catches both cases for Python 2 and 3.

**Comment by joidegn** [comment]
Thanks! I will have a look later today.

**Comment by joidegn** [comment]
Looks great!

**Comment by joidegn** [comment]
I made a release on pypi

**Comment by garfieldnate** [comment]
Wow! Great! It's quite rewarding to have a maintainer accept changes and do a new release so quickly!

I may come back and integrate `pager` so users don't have to pipe to less.

**Pull request merged**
